GET http://localhost:3000/api/V1/announce/creat
//Content-type : application/json


//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTUyNjQ4NDUsImV4cCI6MTc0NjgyMjQ0NSwiYXVkIjoiMDAwMDIzOTAwMCIsImlzcyI6InBpY2t1cnBhZ2UuY29tIn0.80yiQcoTOdorfJ72kHWPeW3lmc0wLHXe0GdBRDH_abU











//await signupVal.validateAsync(


    //"refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTM4OTMwMzgsImV4cCI6MTc0NTQ1MDYzOCwiYXVkIjoiMDAwMDAwMDAwMCIsImlzcyI6InBpY2t1cnBhZ2UuY29tIn0.na0ehKIK9DnLr_YjfGho2CAKXbrIFXfwXxawMX8lJRE"











