post http://localhost:3000/api/V1/auth/login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTUyNjM5MDAsImV4cCI6MTc0NjgyMTUwMCwiYXVkIjoiMDAwMDIzODAwMCIsImlzcyI6InBpY2t1cnBhZ2UuY29tIn0.M-caYedmA--GUUX0MGzWb7Wbin0uHW9T8onTRM10Loc
Content-type : application/json

{
    "full_name": "Jkdsjlkd",
    "phone": "0000238000",
    "password": "94jhgjy"

}










//await signupVal.validateAsync(


    //"refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTM4OTMwMzgsImV4cCI6MTc0NTQ1MDYzOCwiYXVkIjoiMDAwMDAwMDAwMCIsImlzcyI6InBpY2t1cnBhZ2UuY29tIn0.na0ehKIK9DnLr_YjfGho2CAKXbrIFXfwXxawMX8lJRE"











