-- AlterTable
ALTER TABLE "request" ALTER COLUMN "full_name" SET DEFAULT '',
ALTER COLUMN "phone" SET DEFAULT '',
ALTER COLUMN "region" SET DEFAULT '',
ALTER COLUMN "type" SET DEFAULT '',
ALTER COLUMN "lowest_price" SET DEFAULT 0,
ALTER COLUMN "hieghest_price" SET DEFAULT 0,
ALTER COLUMN "location" SET DEFAULT '',
ALTER COLUMN "message" SET DEFAULT '',
ALTER COLUMN "status" SET DEFAULT false;
