-- AlterTable
ALTER TABLE "property" ADD COLUMN     "softDelete" BOOLEAN NOT NULL DEFAULT false,
ALTER COLUMN "price" SET DEFAULT 0,
ALTER COLUMN "price" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "photo" SET DEFAULT '{}';
