POST  http://localhost:3000/api/V1/announce/creatAnnounce
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MjkyNzYyNDcsImV4cCI6MTc2MDgzMzg0NywiYXVkIjoiMDkxODE3MTE2OTAiLCJpc3MiOiJwaWNrdXJwYWdlLmNvbSJ9.YegOi_lem_SQPVs3vbK4stLLvI2-psFisdVQVQk5N2k

{
  "type": "appartemen",
  "region": "appartement",
  "address": "appartement",
  "location": "appartement",
  "usage": "appartement",
  "document_type": "kjljl",
  "land_metrage": 9,
  "useful_metrage": 87,
  "floor_number": 90 ,
  "floor": 67,
  "Unit_in_floor": 9,
  "year_of_build": 9,
  "full_name": "appartement",
  "price": 8999889.7,
  "room_number": 98,
  "features": "09181711690"
}
