Post  http://localhost:3000/api/V1/announce/creatAnnounce
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzAxODMyOTUsImV4cCI6MTc2MTc0MDg5NSwiYXVkIjoiMDkxODE3MTE2OTAiLCJpc3MiOiJwaWNrdXJwYWdlLmNvbSJ9.QCU_pT-mQ9mSEuNrr0fPDpA7FzXHRW_kA2XKKp_jJRc

{
  "loan" : 0,
  "type" : "appartement",
  "region" : "appartement",
  "address" : "appartement",
  "location" : "appartement",
  "usage" : "appartement",
  "document_type" : "appartement",
  "land_metrage" : 78,
  "useful_metrage" : 87,
  "floor_number" : 7,
  "floor" : 2,
  "Unit_in_floor" : 9,
  "year_of_build" : 9,
  "full_name" : "appartement",
  "price"     : 9890,
  "room_number"  : 98,
  "features"     : "9181711690"
}



