post http://localhost:3000/api/V1/request/creatrequest
Content-type : application/json

{
  "full_name" : "skaljd",
  "phone" : "09181711690",
  "region" : "akdlskdsa",
  "type" : "String @default()",
  "lowest_price" : 8282.9 ,
  "hieghest_price" : 92393 ,
  "location" : "String @default()",
  "Message" :  "String @default()"
}