post http://localhost:3000/api/V1/admin/creatdeal
Content-type : application/json

{
    "seller" : "slkjd",
    "region" : "sal",
    "type" : "kladjslda", 
    "number " : "8902", 
    "client" : "adjkklads",
    "price" : 19821,
    "commission" : 12791,
    "date" : "asdjlka",
    "note" :
}











