POST  http://localhost:3000/auth/login
Content-type : application/json



{
    //"full_name": "akdsjlkds",
    "phone": "8181711690",
    "password": "94jhgjy"
}



















































































